steps:
  - step_name: "initial_idea"
    description: |
      ### Step 1: Description Information
      **Objective:** Assist in conceptualizing and organizing Mercedes-Benz's initial patent ideas.
      **Core Issues to Address:**
      [Describe the technical problems or needs in detail.]
      **Task Instructions:**
      As a **Stanford University graduate Tesla Data Scientist** and **CATL Electrochemical Expert**, consider my viewpoint and help me think through and improve this idea. The output should be highly logical, creative, and critically analytical.
      **Requirements:**
      1. Provide at least three specific improvement suggestions.
      2. Each suggestion should include detailed explanations and potential technical implementation methods.
    expected_output: |
      A detailed list of at least three specific improvement suggestions. Each suggestion must include a clear explanation and outline potential technical implementation methods.
    max_tokens: 600

  - step_name: "innovation"
    description: |
      ### Step 2: Interactive Innovation Mining
      **Task Background:** Based on the initial idea, identify and mine new patentable innovations.
      **Task Instructions:**
      As a **Top OpenAI Prompt Engineer**, ask effective questions and discover at least three new patent innovations. Describe each innovation's uniqueness and potential applications in detail.
      **Requirements:**
      1. Each innovation should include background information, innovative aspects, and advantages.
      2. Logical clarity, step-by-step, facilitating subsequent patent writing.
      3. Evaluate and select the most feasible and suitable patents for Mercedes.
    expected_output: |
      A detailed list of at least three new patent innovations. Each innovation must include background details, a description of its innovative aspects and advantages, and a feasibility evaluation.
    max_tokens: 900

  - step_name: "qa"
    description: |
      ### Step 3: Raise Common Questions
      **Task Background:** To ensure the comprehensiveness and depth of patent writing, a series of common questions need to be answered.
      **Task Instructions:**
      As a **Senior Patent Expert**, provide detailed answers to the following questions:
      [List of questions]
      **Requirements:**
      1. Each answer should be detailed and specific.
      2. Use professional terminology to ensure accuracy and authority.
    expected_output: |
      Detailed answers to all the common patent questions, covering aspects such as previous work, technical problems solved, related background knowledge or existing technologies, proposed solutions, beneficial effects/advantages, and a brief English abstract summarizing the invention.
    max_tokens: 1200

  - step_name: "customization"
    description: |
      ### Step 4: Technical Details and Patent Writing
      **Task Background:** Based on the previous outputs, design the technical details of the patent and write a complete patent document.
      **Task Instructions:**
      As a **Patent Writer**, collaborate with mathematicians, deep learning researchers, and Mercedes-Benz data scientists to write a patent containing mathematical formulas, rules, and deep learning methods.
      **Requirements:**
      1. Include mathematical formulas formatted for direct use in Word.
      2. Provide detailed technical implementation methods.
      3. Reference existing patent cases to ensure clarity and structure.
    expected_output: |
      A complete patent document written in Chinese that includes detailed technical specifications, mathematical formulas in Word-compatible format, and comprehensive technical implementation details. The document should be structured clearly and should not contain any summary.
    max_tokens: 8000

  - step_name: "deep_improvement"
    description: |
      ### Step 5: Deep Improvement
      **Task Background:** Based on the previous steps, further refine the patent document by focusing on technical depth, feasibility, and novelty.
      **Task Instructions:**
      As a **Senior Electrochemical Expert** and **BMS Battery Management System Specialist**, conduct deep improvements from the following perspectives:
      1. **In-depth Electrochemical Analysis:** Dive into the electrochemical processes, identifying advanced models for battery efficiency, charge/discharge cycles, and energy density improvement. Provide specific mathematical models or formulas for optimizing battery performance.
      2. **BMS Optimization:** Enhance the existing BMS architecture by proposing improved algorithms for energy management, thermal regulation, and fault detection. Include precise control strategies for balancing battery cells and maximizing battery lifespan.
      3. **AI-Driven Data Integration:** Investigate how AI-driven data analysis can optimize BMS operations in real time. Consider the integration of **deep learning models** for predictive maintenance, anomaly detection, and intelligent charge/discharge prediction based on real-time sensor data.
      4. **Benchmarking with Competitors:** Compare this innovation with existing BMS technologies (e.g., from Tesla, CATL) focusing on computational efficiency, adaptability in extreme conditions, and system integration.
      5. **Practical Applicability:** Assess the scalability and industrial applicability of the proposed technology. Analyze deployment in large-scale manufacturing environments and integration with existing Mercedes-Benz systems, including required infrastructure or software modifications.
      **Requirements:**
      1. Provide no less than 4000 words, with deep technical details.
      2. Include mathematical formulas in a format directly usable in Word.
      3. Emphasize logical rigor, feasibility, and real-world applicability.
      4. Ensure all technical aspects are detailed to enhance patentability.
    expected_output: |
      A refined and comprehensive patent document of no less than 4000 words that delves deeply into technical details. The document must include advanced mathematical models (in Word-compatible format), improved BMS optimization strategies, insights on AI-driven data integration, thorough competitor benchmarking, and a detailed analysis of practical applicability.
    max_tokens: 16000
